import {
  User,
  Terminology,
  FewShotExample,
  EvaluationCase,
  EvaluationReview,
  Achievement,
  Conversation,
} from './schema';
import bcrypt from 'bcryptjs';

// Precomputed bcrypt hashes for Admin@12345 and Student@12345
const DEFAULT_PASSWORD_HASH = bcrypt.hashSync('Student@12345', 10);
const ADMIN_PASSWORD_HASH = bcrypt.hashSync('Admin@12345', 10);

export const SEED_USERS: User[] = [
  {
    id: 'user_admin_001',
    name: 'Dr. Priya Sharma (Lead Researcher)',
    email: 'admin@lingualearn.edu',
    passwordHash: ADMIN_PASSWORD_HASH,
    role: 'ADMIN',
    preferredLanguage: 'Hindi',
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 'user_student_001',
    name: 'Rahul Varma (B.Tech CSE 3rd Year)',
    email: 'student@lingualearn.edu',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'STUDENT',
    preferredLanguage: 'Telugu',
    createdAt: '2026-08-10T10:30:00.000Z',
    updatedAt: '2026-08-10T10:30:00.000Z',
  },
  {
    id: 'user_student_002',
    name: 'Swarna Bindhu (B.Tech CSE)',
    email: 'swarnabindhu36@gmail.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'STUDENT',
    preferredLanguage: 'Telugu',
    createdAt: '2026-08-15T10:30:00.000Z',
    updatedAt: '2026-08-15T10:30:00.000Z',
  },
];

export const SEED_ACHIEVEMENTS: Achievement[] = [
  // Tutor & Inquiries
  {
    id: 'ach_first_question',
    title: 'First Step into Tech',
    description: 'Began your technical journey by asking your first question in the AI Tutor.',
    icon: 'Compass',
    criteria: 'Ask 1 question',
    category: 'TUTOR',
    tier: 'BRONZE',
    xpReward: 50,
    targetVal: 1,
    unit: 'question',
  },
  {
    id: 'ach_curious_mind',
    title: 'Inquisitive Scholar',
    description: 'Asked 10 detailed questions exploring computer science mechanisms.',
    icon: 'Sparkles',
    criteria: 'Ask 10 questions',
    category: 'TUTOR',
    tier: 'SILVER',
    xpReward: 150,
    targetVal: 10,
    unit: 'questions',
  },
  {
    id: 'ach_deep_investigator',
    title: 'Deep Investigator',
    description: 'Delved deep into system architecture with 25 technical inquiries.',
    icon: 'Zap',
    criteria: 'Ask 25 questions',
    category: 'TUTOR',
    tier: 'GOLD',
    xpReward: 300,
    targetVal: 25,
    unit: 'questions',
  },

  // Quizzes & Assessments
  {
    id: 'ach_first_quiz',
    title: 'Quiz Novice',
    description: 'Completed your first AI-generated contextual technical assessment.',
    icon: 'Award',
    criteria: 'Complete 1 quiz',
    category: 'QUIZ',
    tier: 'BRONZE',
    xpReward: 75,
    targetVal: 1,
    unit: 'quiz',
  },
  {
    id: 'ach_quiz_veteran',
    title: 'Assessment Veteran',
    description: 'Tested understanding across 5 comprehensive technical quizzes.',
    icon: 'CheckCircle2',
    criteria: 'Complete 5 quizzes',
    category: 'QUIZ',
    tier: 'SILVER',
    xpReward: 200,
    targetVal: 5,
    unit: 'quizzes',
  },
  {
    id: 'ach_quiz_master',
    title: 'Grand Quizmaster',
    description: 'Conquered 10 technical assessments with rigorous AI evaluation.',
    icon: 'Crown',
    criteria: 'Complete 10 quizzes',
    category: 'QUIZ',
    tier: 'GOLD',
    xpReward: 400,
    targetVal: 10,
    unit: 'quizzes',
  },

  // Accuracy & Mastery
  {
    id: 'ach_high_accuracy',
    title: 'Precision Engineer',
    description: 'Maintained an average quiz score of 80% or higher across all tests.',
    icon: 'Target',
    criteria: 'Average score ≥ 80%',
    category: 'ACCURACY',
    tier: 'SILVER',
    xpReward: 200,
    targetVal: 80,
    unit: '% avg score',
  },
  {
    id: 'ach_perfect_score',
    title: 'Flawless Performance',
    description: 'Achieved a perfect 100% score on a challenging computer science quiz.',
    icon: 'Medal',
    criteria: 'Score 100% on any quiz',
    category: 'ACCURACY',
    tier: 'PLATINUM',
    xpReward: 500,
    targetVal: 100,
    unit: '% score',
  },

  // Multilingual Exploration
  {
    id: 'ach_multilingual_explorer',
    title: 'Bilingual Explorer',
    description: 'Learned engineering concepts in at least 2 distinct languages.',
    icon: 'Languages',
    criteria: 'Use 2 languages',
    category: 'MULTILINGUAL',
    tier: 'BRONZE',
    xpReward: 100,
    targetVal: 2,
    unit: 'languages',
  },
  {
    id: 'ach_multilingual',
    title: 'Multilingual Polyglot',
    description: 'Mastered concepts with preserved terminology across 3 or more languages.',
    icon: 'Globe',
    criteria: 'Use 3 languages',
    category: 'MULTILINGUAL',
    tier: 'GOLD',
    xpReward: 350,
    targetVal: 3,
    unit: 'languages',
  },

  // Topic Breadth
  {
    id: 'ach_topic_explorer',
    title: 'Broad Foundations',
    description: 'Explored 5 distinct core CS subjects (OS, DBMS, DSA, Networks, ML).',
    icon: 'BookOpen',
    criteria: 'Explore 5 topics',
    category: 'TOPICS',
    tier: 'BRONZE',
    xpReward: 100,
    targetVal: 5,
    unit: 'topics',
  },
  {
    id: 'ach_10_topics',
    title: 'Polymath in Training',
    description: 'Built deep mastery across 10 distinct technical computer science domains.',
    icon: 'GraduationCap',
    criteria: 'Explore 10 topics',
    category: 'TOPICS',
    tier: 'GOLD',
    xpReward: 350,
    targetVal: 10,
    unit: 'topics',
  },

  // Consistency & Streaks
  {
    id: 'ach_3day_streak',
    title: 'Steady Momentum',
    description: 'Maintained a consistent daily study streak for 3 consecutive days.',
    icon: 'Flame',
    criteria: '3-day streak',
    category: 'STREAK',
    tier: 'BRONZE',
    xpReward: 100,
    targetVal: 3,
    unit: 'days',
  },
  {
    id: 'ach_7day_streak',
    title: 'Relentless Consistency',
    description: 'Studied technical curriculum for 7 consecutive days without interruption.',
    icon: 'TrendingUp',
    criteria: '7-day streak',
    category: 'STREAK',
    tier: 'SILVER',
    xpReward: 250,
    targetVal: 7,
    unit: 'days',
  },
  {
    id: 'ach_14day_master',
    title: 'Unstoppable Scholar',
    description: 'Demonstrated exemplary commitment with a 14-day continuous learning streak.',
    icon: 'ShieldCheck',
    criteria: '14-day streak',
    category: 'STREAK',
    tier: 'PLATINUM',
    xpReward: 500,
    targetVal: 14,
    unit: 'days',
  },
];

export const SEED_TERMINOLOGY: Terminology[] = [
  {
    id: 'term_01',
    englishTerm: 'API (Application Programming Interface)',
    language: 'Hindi',
    preferredTranslation: 'API (एप्लिकेशन प्रोग्रामिंग इंटरफेस)',
    alternativeTranslations: ['प्रोग्रामिंग इंटरफेस', 'एपीआई'],
    doNotTranslate: true,
    subject: 'Software Engineering',
    explanation: 'Preserve "API". Do not translate to "अनुप्रयोग क्रमादेशन अंतराफलक" as it confuses developers. Explain it as software components ke beech ka contract/connector.',
    technicalMeaning: 'An Application Programming Interface (API) is a formalized computing interface that defines interactions between multiple software intermediaries, specifying the types of calls or requests that can be made, data formats (e.g. JSON/Protocol Buffers), and conventions to follow.',
    technicalExample: `// RESTful API Endpoint in Express (Node.js)
app.get('/api/v1/students/:id', async (req, res) => {
  const student = await db.students.findById(req.params.id);
  if (!student) return res.status(404).json({ error: 'Student not found' });
  res.json({ status: 200, data: student });
});`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_02',
    englishTerm: 'API (Application Programming Interface)',
    language: 'Telugu',
    preferredTranslation: 'API (అప్లికేషన్ ప్రోగ్రామింగ్ ఇంటర్‌ఫేస్)',
    alternativeTranslations: ['ఏపీఐ', 'సాఫ్ట్‌వేర్ ఇంటర్‌ఫేస్'],
    doNotTranslate: true,
    subject: 'Software Engineering',
    explanation: 'Keep API as English term or transliteration. Literal Telugu translation like అనువర్తన అనుసంధానం causes loss of technical precision.',
    technicalMeaning: 'An API defines the contract and network protocols (HTTP/REST, gRPC, WebSocket) through which external clients interact with backend microservices without exposing internal database implementation details.',
    technicalExample: `// Consuming an API endpoint in client-side code
async function fetchCourseData(courseId) {
  const response = await fetch(\`https://api.lingualearn.edu/courses/\${courseId}\`, {
    headers: { 'Authorization': 'Bearer token_xyz' }
  });
  return await response.json();
}`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_03',
    englishTerm: 'Thread',
    language: 'Hindi',
    preferredTranslation: 'Thread (थ्रेड - निष्पादन की सबसे छोटी इकाई)',
    alternativeTranslations: ['निष्पादन थ्रेड'],
    doNotTranslate: true,
    subject: 'Operating Systems',
    explanation: 'Never translate "Thread" as "धागा" (sewing string). A Thread is the smallest unit of execution inside a Process.',
    technicalMeaning: 'A Thread is the smallest execution unit capable of being scheduled by an operating system. Multiple threads in a process share the parent process address space (code, heap, global data), but possess private registers and call stacks.',
    technicalExample: `// POSIX Thread (pthread) in C
#include <pthread.h>
#include <stdio.h>

void* worker(void* arg) {
    printf("Worker thread executing inside process PID: %d\\n", getpid());
    return NULL;
}
int main() {
    pthread_t tid;
    pthread_create(&tid, NULL, worker, NULL);
    pthread_join(tid, NULL);
}`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_04',
    englishTerm: 'Deadlock',
    language: 'Telugu',
    preferredTranslation: 'Deadlock (డెడ్‌లాక్ - నిలిచిపోయిన పరిస్థితి)',
    alternativeTranslations: ['రిసోర్స్ బ్లాకింగ్', 'డెడ్‌లాక్'],
    doNotTranslate: true,
    subject: 'Operating Systems',
    explanation: 'Preserve "Deadlock". Literal translation like "మరణించిన తాళం" is absurd. Explain it as processes circular wait lo stuck avvadam.',
    technicalMeaning: 'A Deadlock is an operating system state where two or more processes cannot make forward progress because each is waiting for a resource held by another process in the set, fulfilling Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait.',
    technicalExample: `// Deadlock generation in concurrent execution:
// Thread 1 acquires Mutex A, then requests Mutex B.
// Thread 2 acquires Mutex B, then requests Mutex A.
// Result: Both threads block indefinitely in Circular Wait.`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_05',
    englishTerm: 'Recursion',
    language: 'Hindi',
    preferredTranslation: 'Recursion (रिकर्शन / पुनरावर्तन)',
    alternativeTranslations: ['स्व-आह्वान'],
    doNotTranslate: false,
    subject: 'Data Structures',
    explanation: 'Use Recursion with Hindi explanation of a function calling itself until a base condition is met.',
    technicalMeaning: 'Recursion is a programming paradigm where a method solves a computational problem by reducing it to smaller sub-problems and invoking itself, relying on the runtime call stack until satisfying a designated base condition.',
    technicalExample: `// Binary Search using Recursive Call Stack
int binarySearch(int arr[], int low, int high, int key) {
    if (low > high) return -1; // Base case
    int mid = low + (high - low) / 2;
    if (arr[mid] == key) return mid;
    if (arr[mid] > key) return binarySearch(arr, low, mid - 1, key);
    return binarySearch(arr, mid + 1, high, key);
}`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_06',
    englishTerm: 'Overfitting',
    language: 'Tamil',
    preferredTranslation: 'Overfitting (ஓவர்ஃபிட்டிங் / அதிகப்படியான பொருத்தம்)',
    alternativeTranslations: ['அளவுக்கு அதிகமான பொருத்தம்'],
    doNotTranslate: true,
    subject: 'Machine Learning',
    explanation: 'Overfitting must be preserved as ML term. Translating literally as dress fitting obscures ML training vs testing error.',
    technicalMeaning: 'Overfitting is an empirical machine learning failure mode where a complex model learns training dataset noise and idiosyncratic features rather than true general underlying distributions, resulting in low training loss but high generalization validation error.',
    technicalExample: `// Combating Overfitting with L2 Weight Decay in PyTorch
import torch.nn as nn
import torch.optim as optim

model = nn.Sequential(nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 10))
# weight_decay parameter applies L2 regularization penalty to prevent overfitting
optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_07',
    englishTerm: 'Database Normalization',
    language: 'Hindi',
    preferredTranslation: 'Database Normalization (डेटाबेस सामान्यीकरण / नॉर्मलाइज़ेशन)',
    alternativeTranslations: ['नॉर्मलाइज़ेशन', 'रिडंडेंसी न्यूनीकरण'],
    doNotTranslate: false,
    subject: 'DBMS',
    explanation: 'Explain as table design process to eliminate redundancy and anomaly (1NF, 2NF, 3NF, BCNF).',
    technicalMeaning: 'Database Normalization is the formal mathematical technique of organizing relational database schema tables to minimize functional data redundancy and eliminate insert, update, and deletion anomalies via progressive Normal Forms.',
    technicalExample: `-- 3NF Table Normalization Example:
-- Decomposing unnormalized Orders table into independent Entities
CREATE TABLE Customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100),
    city VARCHAR(50)
);
CREATE TABLE Orders (
    order_id INT PRIMARY KEY,
    customer_id INT REFERENCES Customers(customer_id),
    order_date DATE,
    total_amount DECIMAL(10, 2)
);`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_08',
    englishTerm: 'TCP/IP (Transmission Control Protocol / Internet Protocol)',
    language: 'Kannada',
    preferredTranslation: 'TCP/IP (ಟಿ.ಸಿ.ಪಿ/ಐ.ಪಿ ಪ್ರೊಟೊಕಾಲ್)',
    alternativeTranslations: ['ನೆಟ್‌ವರ್ಕ್ ಪ್ರೋಟೋಕಾಲ್'],
    doNotTranslate: true,
    subject: 'Computer Networks',
    explanation: 'Standard networking protocol stack. Do not attempt literal word-for-word Kannada translations.',
    technicalMeaning: 'TCP/IP is the foundational four-layer communication protocol architecture (Application, Transport, Internet, Network Interface) governing packet-switched inter-network communications, guaranteeing ordered, error-checked packet delivery via TCP.',
    technicalExample: `// TCP 3-Way Handshake Connection Sequence:
// Host A (Client) -----> [SYN, Seq=100] ------------> Host B (Server)
// Host A <---------- [SYN-ACK, Seq=300, Ack=101] ---- Host B
// Host A --------------> [ACK, Ack=301] --------------> Host B
// [Established]: Reliable full-duplex socket stream active`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_09',
    englishTerm: 'Compiler',
    language: 'Bengali',
    preferredTranslation: 'Compiler (কম্পাইলার)',
    alternativeTranslations: ['সোর্স কোড অনুবাদক'],
    doNotTranslate: true,
    subject: 'Programming',
    explanation: 'Translates high-level source code into machine code in one complete pass.',
    technicalMeaning: 'A Compiler is a language translation system that translates high-level programming language statements into low-level target machine code or assembly through lexical analysis, syntax parsing, semantic validation, intermediate code optimization, and code generation.',
    technicalExample: `// Invoking the LLVM/Clang compiler with optimization flags
$ clang -O3 -Wall main.c -o application_binary
// Step 1: Preprocessing -> main.i
// Step 2: Lexical & Parsing -> Abstract Syntax Tree (AST)
// Step 3: LLVM IR Bytecode -> Machine Code Generation`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_10',
    englishTerm: 'Socket',
    language: 'Hindi',
    preferredTranslation: 'Socket (नेटवर्क सॉकेट - IP + Port)',
    alternativeTranslations: ['कम्युनिकेशन एंडपॉइंट'],
    doNotTranslate: true,
    subject: 'Computer Networks',
    explanation: 'Do not translate to bijli ka switchboard/plughole. It is an IP address plus Port number endpoint for bidirectional communication.',
    technicalMeaning: 'A Network Socket is an operating system abstraction representing an endpoint of a two-way inter-process communication link across an IP network, uniquely identified by the 5-tuple: (Source IP, Source Port, Destination IP, Destination Port, Protocol).',
    technicalExample: `// Python TCP Socket Server
import socket
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind(('0.0.0.0', 9000))
server.listen(5)
conn, addr = server.accept()
print(f"Accepted connection from client: {addr}")
conn.sendall(b"HTTP/1.1 200 OK\\r\\n\\r\\nHello Network")`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_11',
    englishTerm: 'Virtual Memory',
    language: 'Marathi',
    preferredTranslation: 'Virtual Memory (व्हर्च्युअल मेमरी / आभासी मेमरी)',
    alternativeTranslations: ['आभासी मेमरी'],
    doNotTranslate: false,
    subject: 'Operating Systems',
    explanation: 'Operating system abstraction creating illusion of large contiguous address space using paging and swap space.',
    technicalMeaning: 'Virtual Memory is an operating system memory virtualization mechanism that maps process virtual addresses to physical RAM frames or swap disk space using hardware MMUs and multi-level page tables, isolating process address spaces.',
    technicalExample: `// Virtual Memory Page Translation Hierarchy (x86-64):
// CR3 Register -> PML4 (512GB) -> PDPT (1GB) -> PD (2MB) -> PT (4KB page)
// If hardware MMU finds Valid Bit = 0 in Page Table Entry:
// Triggers Page Fault Exception (Interrupt 14); OS swaps page in from disk.`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_12',
    englishTerm: 'Neural Network',
    language: 'Telugu',
    preferredTranslation: 'Neural Network (న్యూరల్ నెట్‌వర్క్ / కృత్రిమ నాడీ వ్యవస్థ)',
    alternativeTranslations: ['ఆర్టిఫిషియల్ న్యూరల్ నెట్‌వర్క్', 'న్యూరల్ నెట్‌వర్క్'],
    doNotTranslate: false,
    subject: 'Artificial Intelligence',
    explanation: 'Computational model inspired by biological brain neurons with input, hidden, and output layers.',
    technicalMeaning: 'An Artificial Neural Network (ANN) is a parameterized non-linear function approximator composed of interconnected layers of artificial neurons that transform input tensors via learned weight matrices, biases, and non-linear activation functions.',
    technicalExample: `// Multi-Layer Perceptron (MLP) in PyTorch
import torch.nn as nn
class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(784, 128)
        self.act = nn.ReLU()
        self.output = nn.Linear(128, 10)
    def forward(self, x):
        return self.output(self.act(self.layer1(x)))`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_13',
    englishTerm: 'Garbage Collection',
    language: 'Hindi',
    preferredTranslation: 'Garbage Collection (गार्बेज कलेक्शन - ऑटोमैटिक मेमोरी रिक्लेमेशन)',
    alternativeTranslations: ['मेमोरी क्लीयरेंस'],
    doNotTranslate: true,
    subject: 'Programming',
    explanation: 'Do not translate as kachra uthana (sanitation). It is the runtime automatic freeing of heap memory no longer referenced.',
    technicalMeaning: 'Garbage Collection (GC) is an automatic runtime memory management mechanism that detects heap-allocated memory objects that are no longer reachable from any execution stack root references and automatically reclaims their memory space.',
    technicalExample: `// JVM Generational Garbage Collection:
// 1. Objects allocated in Eden (Young Generation).
// 2. Surviving objects copied to Survivor Spaces (S0/S1).
// 3. Long-lived objects promoted to Tenured (Old Generation).
// 4. Mark-and-Sweep algorithm frees unreferenced objects automatically.`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_14',
    englishTerm: 'B-Tree Indexing',
    language: 'Gujarati',
    preferredTranslation: 'B-Tree Indexing (બી-ટ્રી ઇન્ડેક્સિંગ)',
    alternativeTranslations: ['ડેટાબેઝ ઇન્ડેક્સ'],
    doNotTranslate: true,
    subject: 'DBMS',
    explanation: 'Self-balancing tree data structure that maintains sorted data and allows searches, sequential access, insertions, and deletions in logarithmic time.',
    technicalMeaning: 'A B-Tree is a self-balancing balanced multiway search tree optimized for storage systems that read and write large blocks of data, keeping keys sorted and supporting O(log n) searches, range queries, and sequential traversals with minimal disk I/O.',
    technicalExample: `-- Creating a B-Tree index on a relational database column
CREATE INDEX idx_user_registration ON users USING btree (created_at DESC);
-- Enables instant index range scan instead of full table sequential scan:
EXPLAIN SELECT * FROM users WHERE created_at >= '2026-01-01';`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_15',
    englishTerm: 'Buffer Overflow',
    language: 'Punjabi',
    preferredTranslation: 'Buffer Overflow (ਬਫਰ ਓਵਰਫਲੋਅ)',
    alternativeTranslations: ['ਮੈਮੋਰੀ ਸੀਮਾ ਉਲੰਘਣਾ'],
    doNotTranslate: true,
    subject: 'Cyber Security',
    explanation: 'Security vulnerability where written data exceeds allocated buffer memory block and corrupts adjacent memory registers.',
    technicalMeaning: 'A Buffer Overflow is an anomalous memory condition occurring when an application writes data past the boundary of a fixed-size allocated buffer, corrupting adjacent stack frames, return address registers, or heap control blocks.',
    technicalExample: `// Vulnerable C code lacking bounds enforcement
void vulnerable_copy(char *user_input) {
    char local_buffer[32];
    strcpy(local_buffer, user_input); // Unsafe: overflows if user_input > 32 bytes!
}
// Secure defense:
strncpy(local_buffer, user_input, sizeof(local_buffer) - 1);`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_16',
    englishTerm: 'Semaphore',
    language: 'Telugu',
    preferredTranslation: 'Semaphore (సెమాఫోర్ - సమన్వయ వేరియబుల్)',
    alternativeTranslations: ['సింక్రొనైజేషన్ వేరియబుల్', 'సెమాఫోర్'],
    doNotTranslate: true,
    subject: 'Operating Systems',
    explanation: 'Preserve "Semaphore". Do not translate as railway flag. It is an integer synchronization counter with atomic wait() and signal() operations.',
    technicalMeaning: 'A Semaphore is an operating system synchronization abstraction that controls concurrent access to a shared resource pool using atomic P() [wait] and V() [signal] operations on an integer counter.',
    technicalExample: `// POSIX Counting Semaphore in C
sem_t printer_pool;
sem_init(&printer_pool, 0, 4); // 4 printers available
sem_wait(&printer_pool);       // Decrement counter, wait if none available
// Print job executing in critical section...
sem_post(&printer_pool);       // Release printer, increment counter`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_17',
    englishTerm: 'Mutex (Mutual Exclusion Lock)',
    language: 'Hindi',
    preferredTranslation: 'Mutex (म्यूटेक्स - म्यूचुअल एक्सक्लूज़न लॉक)',
    alternativeTranslations: ['म्यूचुअल एक्सक्लूज़न', 'बाइनरी लॉक'],
    doNotTranslate: true,
    subject: 'Operating Systems',
    explanation: 'Preserve "Mutex". It is a binary locking primitive where only the thread that acquired the lock may release it.',
    technicalMeaning: 'A Mutex is a mutual exclusion locking primitive designed for concurrency control, guaranteeing that at most one thread executes within a designated critical section at any instant.',
    technicalExample: `// std::mutex lock guard in C++
#include <mutex>
std::mutex balance_mutex;
void updateBalance(double delta) {
    std::lock_guard<std::mutex> lock(balance_mutex);
    account_balance += delta; // Thread-safe atomic update
}`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'term_18',
    englishTerm: 'ACID Properties',
    language: 'Telugu',
    preferredTranslation: 'ACID Properties (యాసిడ్ ప్రాపర్టీస్ - డేటాబేస్ ప్రమాణాలు)',
    alternativeTranslations: ['డేటాబేస్ లావాదేవీల నియమాలు'],
    doNotTranslate: true,
    subject: 'DBMS',
    explanation: 'Preserve ACID. Do not translate as chemical acid (ఆమ్లము). In DBMS, it guarantees transaction reliability (Atomicity, Consistency, Isolation, Durability).',
    technicalMeaning: 'ACID properties (Atomicity, Consistency, Isolation, Durability) are the four fundamental transaction processing guarantees that ensure database validity and reliability despite network failures or crashes.',
    technicalExample: `-- Relational ACID Transaction block
BEGIN TRANSACTION;
UPDATE accounts SET balance = balance - 1000 WHERE id = 42;
UPDATE accounts SET balance = balance + 1000 WHERE id = 88;
COMMIT; -- Changes flushed to Write-Ahead Log ensuring Durability`,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
];

export const SEED_FEW_SHOT_EXAMPLES: FewShotExample[] = [
  {
    id: 'few_01',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    subject: 'Operating Systems',
    difficulty: 'INTERMEDIATE',
    question: 'What is a Semaphore and how does it prevent race conditions?',
    expectedStyle: 'Technical Hindi preserving OS terms (Semaphore, Mutex, Race Condition, Critical Section, wait/signal)',
    terminologyGuidance: 'Do not translate Semaphore to "संकेत ध्वज". Keep Semaphore, wait(), signal() intact with code/pseudocode example.',
    responseSnippet: 'Semaphore एक synchronization tool है जो critical section में race conditions को रोकता है...',
    enabled: true,
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'few_02',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    subject: 'Data Structures',
    difficulty: 'BEGINNER',
    question: 'How does a Stack data structure work?',
    expectedStyle: 'Friendly technical Telugu with LIFO analogy (plates stack), keeping Push, Pop, Peek, Top as keywords.',
    terminologyGuidance: 'Keep Stack, Push, Pop, LIFO in English script or clear Telugu transliteration (స్టాక్, పుష్, పాప్).',
    responseSnippet: 'Stack అనేది ఒక Linear Data Structure, ఇది LIFO (Last In First Out) నియమం పై పనిచేస్తుంది...',
    enabled: true,
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'few_03',
    sourceLanguage: 'English',
    targetLanguage: 'Tamil',
    subject: 'DBMS',
    difficulty: 'ADVANCED',
    question: 'Explain ACID properties in relational database transactions.',
    expectedStyle: 'Rigorous technical Tamil maintaining Atomicity, Consistency, Isolation, Durability, WAL, 2PL, Commit, Rollback.',
    terminologyGuidance: 'Do not create confusing literal translations for Isolation or Durability without contextualizing DBMS transaction states.',
    responseSnippet: 'ACID Properties என்பது Database Transactions-இன் நம்பகத்தன்மையை உறுதி செய்யும் நான்கு முக்கிய பண்புகள்...',
    enabled: true,
    createdAt: '2026-08-01T00:00:00.000Z',
  },
];

export const SEED_EVALUATION_CASES: EvaluationCase[] = [
  {
    id: 'case_001',
    subject: 'Operating Systems',
    topic: 'Thread Synchronization',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'What is a Thread in an operating system and why do multithreaded applications experience race conditions?',
    referenceAnswer: 'A thread is the smallest unit of CPU execution within a process sharing heap memory and global variables. Race conditions happen when multiple threads read and write shared data concurrently without mutex locks.',
    directTranslation: 'ऑपरेटिंग सिस्टम में धागा क्या है और बहु-धागा अनुप्रयोग दौड़ की स्थिति का अनुभव क्यों करते हैं? एक धागा निष्पादन की सुई है जो प्रक्रिया में कपड़े सिलती है...',
    contextAwareResponse: 'Operating System में Thread किसी Process के निष्पादन (execution) की सबसे छोटी इकाई (lightweight process) होती है। सभी Threads एक ही Process के address space और shared heap memory को share करते हैं। जब दो या अधिक Threads बिना किसी Synchronization (जैसे Mutex या Semaphore) के एक साथ shared variable पर read/write करते हैं, तो Race Condition उत्पन्न होती है...',
    expectedTerms: ['Thread', 'Process', 'Race Condition', 'Shared Memory', 'Mutex / Lock'],
    createdAt: '2026-08-15T09:00:00.000Z',
  },
  {
    id: 'case_002',
    subject: 'Computer Networks',
    topic: 'Network Sockets',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    question: 'Explain what a network socket is and how TCP three-way handshaking works.',
    referenceAnswer: 'A socket is an endpoint combining IP address and port number for inter-process communication. TCP 3-way handshake uses SYN, SYN-ACK, and ACK packets to establish reliable full-duplex connection.',
    directTranslation: 'నెట్‌వర్క్ సాకెట్ అనేది ఒక విద్యుత్ ప్లగ్ బోర్డు. TCP మూడు వైపులా కరచాలనం చేయడం అనేది సర్వర్‌లో ప్లగ్ పెట్టడం ద్వారా జరుగుతుంది...',
    contextAwareResponse: 'Network Socket అనేది రెండు కంప్యూటర్ల మధ్య నెట్‌వర్క్ ద్వారా కమ్యూనికేషన్ జరిగే ఒక Endpoint. ఇది IP Address మరియు Port Number కలయికతో రూపొందుతుంది (ఉదా: 192.168.1.10:8080). TCP Three-Way Handshake అనేది కనెక్షన్ ఏర్పాటు చేయడానికి వాడే పద్ధతి: 1) Client నుండి SYN ప్యాకెట్, 2) Server నుండి SYN-ACK ప్యాకెట్, 3) Client నుండి ACK ప్యాకెట్ పంపి Reliable Connection నిర్ధారిస్తుంది...',
    expectedTerms: ['Socket', 'IP Address', 'Port Number', 'TCP Three-Way Handshake', 'SYN', 'ACK'],
    createdAt: '2026-08-15T09:15:00.000Z',
  },
  {
    id: 'case_003',
    subject: 'Machine Learning',
    topic: 'Overfitting and Regularization',
    sourceLanguage: 'English',
    targetLanguage: 'Tamil',
    question: 'What is overfitting in machine learning and how does L2 regularization prevent it?',
    referenceAnswer: 'Overfitting occurs when an ML model memorizes training noise instead of general patterns, yielding high train accuracy and poor test accuracy. L2 regularization penalizes large weight magnitudes using squared weight penalties.',
    directTranslation: 'இயந்திரக் கற்றலில் அதிகப்படியான ஆடை பொருத்துதல் என்றால் என்ன? L2 ஒழுங்குமுறை என்பது தையல் இயந்திரத்தை இறுக்குவதாகும்...',
    contextAwareResponse: 'Machine Learning-இல் Overfitting என்பது ஒரு Model, Training Data-வில் உள்ள Noise மற்றும் நுணுக்கங்களை மிக அதிகமாக மனப்பாடம் (memorize) செய்துவிட்டு, புதிய Test Data-வில் மோசமாக செயல்படும் நிலை (High Variance). L2 Regularization (Ridge) என்பது Loss Function-உடன் Weights-இன் வர்க்கத்தை (λ * Σw²) அபராதமாக (penalty) சேர்த்து, மாடல் எடைகள் தேவையின்றி பெரிதாவதைத் தடுத்து Generalization-ஐ மேம்படுத்துகிறது...',
    expectedTerms: ['Overfitting', 'Machine Learning', 'Training Data', 'Test Data', 'L2 Regularization', 'Weights Penalty'],
    createdAt: '2026-08-15T09:30:00.000Z',
  },
  {
    id: 'case_004',
    subject: 'Data Structures',
    topic: 'Hash Collisions',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'How do Hash Tables resolve hash collisions using Separate Chaining vs Open Addressing?',
    referenceAnswer: 'Hash collision occurs when two distinct keys yield identical hash index. Separate chaining stores colliding elements in a linked list at the bucket, while open addressing probes for the next available array index.',
    directTranslation: 'हैश टेबल हैश टक्कर को अलग जंजीर और खुले संबोधन से कैसे सुलझाती हैं? जब दो चाबियां एक ही ताले में टकराती हैं तो जंजीर बांध दी जाती है...',
    contextAwareResponse: 'Hash Table में जब दो अलग Keys का hash function एक ही bucket index generate करता है, तो उसे Hash Collision कहते हैं। Separate Chaining में हर bucket index पर एक Linked List बनाई जाती है जहाँ colliding elements स्टोर होते हैं। Open Addressing (Linear/Quadratic Probing) में यदि index भरा हो, तो array के अगले खाली slot की खोज (probe) करके element स्टोर किया जाता है...',
    expectedTerms: ['Hash Table', 'Hash Collision', 'Separate Chaining', 'Open Addressing', 'Linked List', 'Probing'],
    createdAt: '2026-08-15T09:45:00.000Z',
  },
  {
    id: 'case_005',
    subject: 'Operating Systems',
    topic: 'Deadlock Conditions',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    question: 'What are Coffman four conditions required for deadlock to occur in an operating system?',
    referenceAnswer: 'Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait must simultaneously hold for a deadlock to happen.',
    directTranslation: 'ఆపరేటింగ్ సిస్టమ్‌లో మరణించిన తాళం పడటానికి కాఫ్‌మన్ నాలుగు షరతులు ఏమిటి? పరస్పర బహిష్కరణ, పట్టుకుని వేచి ఉండటం...',
    contextAwareResponse: 'Operating System లో Deadlock సంభవించడానికి Coffman పేర్కొన్న 4 తప్పనిసరి షరతులు (Conditions): 1) Mutual Exclusion (వనరు కేవలం ఒక Process కే అందుబాటులో ఉండాలి), 2) Hold and Wait (ఒక వనరును పట్టుకుని మరొకదాని కోసం వేచి ఉండటం), 3) No Preemption (బలవంతంగా వనరును తీసుకోలేకపోవడం), 4) Circular Wait (సైక్లిక్ క్రమంలో ఒకరి వనరు కోసం మరొకరు నిరీక్షించడం)...',
    expectedTerms: ['Deadlock', 'Coffman Conditions', 'Mutual Exclusion', 'Hold and Wait', 'No Preemption', 'Circular Wait'],
    createdAt: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'case_006',
    subject: 'DBMS',
    topic: 'ACID Properties',
    sourceLanguage: 'English',
    targetLanguage: 'Kannada',
    question: 'Explain the ACID properties of database transactions with real banking examples.',
    referenceAnswer: 'Atomicity (all or nothing), Consistency (preserves invariants), Isolation (concurrent transactions execute without interference), Durability (committed changes persist even after crash).',
    directTranslation: 'ಡೇಟಾಬೇಸ್ ವಹಿವಾಟುಗಳ ಆಮ್ಲ ಗುಣಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ. ಪರಮಾಣುತೆ, ಸ್ಥಿರತೆ, ಪ್ರತ್ಯೇಕತೆ ಮತ್ತು ಬಾಳಿಕೆ...',
    contextAwareResponse: 'Database Management System ನಲ್ಲಿ Transaction ನ ವಿಶ್ವಾಸಾರ್ಹತೆ ಕಾಪಾಡಲು ACID Properties ಅತ್ಯಗತ್ಯ: 1) Atomicity (ಎಲ್ಲವೂ ಪೂರ್ಣಗೊಳ್ಳಬೇಕು ಅಥವಾ ರೋಲ್‌ಬ್ಯಾಕ್ ಆಗಬೇಕು - All or Nothing), 2) Consistency (ಖಾತೆ ಬ್ಯಾಲೆನ್ಸ್ ನಿಯಮಗಳು ಸ್ಥಿರವಾಗಿರಬೇಕು), 3) Isolation (ಎರಡು ವಹಿವಾಟುಗಳು ಏಕಕಾಲದಲ್ಲಿ ನಡೆದರೂ ಪರಸ್ಪರ ಹಸ್ತಕ್ಷೇಪ ಮಾಡಬಾರದು), 4) Durability (Commit ಆದ ಡೇಟಾ ಸಿಸ್ಟಮ್ ಕ್ರ್ಯಾಶ್ ಆದರೂ ಸುರಕ್ಷಿತವಾಗಿ ಉಳಿಯಬೇಕು)...',
    expectedTerms: ['ACID Properties', 'Atomicity', 'Consistency', 'Isolation', 'Durability', 'Transaction', 'Commit', 'Rollback'],
    createdAt: '2026-08-15T10:15:00.000Z',
  },
  {
    id: 'case_007',
    subject: 'Algorithms',
    topic: 'Dijkstra Shortest Path',
    sourceLanguage: 'English',
    targetLanguage: 'Bengali',
    question: 'How does Dijkstra algorithm find the shortest path in a weighted graph and why does it fail with negative weights?',
    referenceAnswer: 'Dijkstra greedily picks unvisited node with minimum tentative distance and relaxes neighbors. It assumes non-negative edge weights; negative weights violate greedy choice property causing suboptimal paths.',
    directTranslation: 'ডিজকস্ট্রা অ্যালগরিদম কীভাবে ওজনযুক্ত গ্রাফে সংক্ষিপ্ততম পথ খুঁজে পায় এবং ঋণাত্মক ওজনে কেন ব্যর্থ হয়? এটি লোভী উপায়ে হাঁটে...',
    contextAwareResponse: 'Dijkstra\'s Algorithm একটি Weighted Graph-এ একটি Single Source থেকে সমস্ত Node-এর Shortest Path গণনা করতে Greedy Approach এবং Priority Queue (Min-Heap) ব্যবহার করে। এটি প্রতি পদক্ষেপে সবচেয়ে কম Distance-এর Node-কে Relax করে। কিন্তু যদি Graph-এ Negative Edge Weight থাকে, তাহলে পূর্বের Finalized Node-এর চেয়েও কম দূরত্বের পথ তৈরি হতে পারে যা Greedy Assumption-কে নষ্ট করে দেয়...',
    expectedTerms: ['Dijkstra Algorithm', 'Weighted Graph', 'Shortest Path', 'Min-Heap / Priority Queue', 'Edge Relaxation', 'Negative Weights'],
    createdAt: '2026-08-15T10:30:00.000Z',
  },
  {
    id: 'case_008',
    subject: 'Artificial Intelligence',
    topic: 'Transformer Attention Mechanism',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'How does the Scaled Dot-Product Self-Attention mechanism work in Transformer neural networks?',
    referenceAnswer: 'Self-attention computes Attention(Q, K, V) = softmax(Q * K^T / sqrt(d_k)) * V, mapping query vectors against key vectors to assign contextual importance weights across token sequence.',
    directTranslation: 'ट्रांसफार्मर तंत्रिका नेटवर्क में स्केल किया गया बिंदु-उत्पाद आत्म-ध्यान तंत्र कैसे काम करता है? यह प्रश्नों और चाबियों को खुद पर ध्यान दिलाता है...',
    contextAwareResponse: 'Transformer architecture में Self-Attention mechanism इनपुट सीक्वेंस के सभी tokens के बीच contextual संबंध स्थापित करता है। इसमें प्रत्येक token के लिए तीन vectors निकाले जाते हैं: Query (Q), Key (K), और Value (V)। इसका सूत्र Attention(Q, K, V) = softmax((Q * K^T) / √d_k) * V होता है, जहाँ √d_k vanishing gradients को रोकने के लिए scaling factor का काम करता है...',
    expectedTerms: ['Transformer', 'Self-Attention', 'Query (Q)', 'Key (K)', 'Value (V)', 'Softmax', 'Scaling Factor'],
    createdAt: '2026-08-15T10:45:00.000Z',
  },
  {
    id: 'case_009',
    subject: 'Cyber Security',
    topic: 'Public Key Cryptography',
    sourceLanguage: 'English',
    targetLanguage: 'Marathi',
    question: 'How does Asymmetric / Public Key Encryption differ from Symmetric Encryption in secure communication?',
    referenceAnswer: 'Symmetric uses a single shared secret key for encryption and decryption, causing key distribution challenges. Asymmetric uses mathematically linked public/private key pairs (RSA, ECC).',
    directTranslation: 'सार्वजनिक की एनक्रिप्शन सममित एनक्रिप्शनपेक्षा कसे वेगळे आहे? एकाच चावीने कुलूप उघडणे आणि दोन चाव्या असणे...',
    contextAwareResponse: 'Symmetric Encryption मध्ये डेटा encrypt आणि decrypt करण्यासाठी एकच Secret Key वापरली जाते (उदा: AES), ज्यामुळे Key Distribution ची मोठी समस्या निर्माण होते. तर Asymmetric (Public Key) Cryptography मध्ये दोन जोडलेल्या Keys असतात: Public Key (जी कोणाशीही share करता येते) आणि Private Key (जी केवळ मालकाकडे सुरक्षित राहते)...',
    expectedTerms: ['Symmetric Encryption', 'Asymmetric Encryption', 'Public Key', 'Private Key', 'Ciphertext', 'Key Exchange'],
    createdAt: '2026-08-15T11:00:00.000Z',
  },
  {
    id: 'case_010',
    subject: 'Cloud Computing',
    topic: 'Containerization vs Virtualization',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    question: 'What is the architectural difference between Docker containers and hypervisor-based virtual machines?',
    referenceAnswer: 'VMs abstract hardware and run full guest OS on hypervisors. Containers virtualize OS kernel level using Linux cgroups and namespaces, sharing host kernel for lightweight isolation.',
    directTranslation: 'డాకర్ డబ్బాలు మరియు వర్చువల్ యంత్రాల మధ్య నిర్మాణ తేడా ఏమిటి? హైపర్‌వైజర్ ఒక పెద్ద గది లాంటిది...',
    contextAwareResponse: 'Virtual Machines (VMs) Hypervisor (Type 1 లేదా Type 2) పై పనిచేస్తూ ప్రతి VM లోనూ పూర్తి Guest Operating System, Virtual Hardware మరియు Kernel కలిగి ఉంటాయి (Heavyweight). దీనికి విరుద్ధంగా, Docker Containers నేరుగా Host OS Kernel ను పంచుకుంటాయి (Linux Namespaces & cgroups ద్వారా Isolation సాధిస్తాయి). దీనివల్ల Containers కొన్ని సెకన్లలోనే బూట్ అవుతాయి...',
    expectedTerms: ['Docker Containers', 'Virtual Machines', 'Hypervisor', 'Guest OS', 'Host Kernel', 'Namespaces & cgroups'],
    createdAt: '2026-08-15T11:15:00.000Z',
  },
  {
    id: 'case_011',
    subject: 'Programming',
    topic: 'Memory Leak & Garbage Collection',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'What is a memory leak in Java or Node.js and how does Mark-and-Sweep Garbage Collection work?',
    referenceAnswer: 'A memory leak happens when unused heap objects remain referenced, preventing GC reclamation. Mark-and-sweep starts from GC roots, traverses live references, and sweeps unreferenced memory.',
    directTranslation: 'जावा में मेमोरी का रिसाव क्या है और कचरा उठाने वाला मार्क और स्वीप कैसे झाड़ू लगाता है? स्मृति से पानी टपकने लगता है...',
    contextAwareResponse: 'Java या Node.js में Memory Leak तब होता है जब Heap memory में मौजूद Objects अब application को आवश्यक नहीं होते, परन्तु किसी active reference (जैसे static collection या uncleared event listeners) के कारण Garbage Collector उन्हें free नहीं कर पाता। Mark-and-Sweep GC Algorithm दो चरणों में कार्य करता है: 1) Mark Phase: GC Root (stack variables, global objects) से शुरू करके सभी reachable objects को mark करता है। 2) Sweep Phase: Unmarked objects की memory को reclaim करके OS को उपलब्ध कराता है...',
    expectedTerms: ['Memory Leak', 'Garbage Collector', 'Heap Memory', 'GC Roots', 'Mark-and-Sweep'],
    createdAt: '2026-08-15T11:30:00.000Z',
  },
  {
    id: 'case_012',
    subject: 'Data Structures',
    topic: 'Red-Black Trees',
    sourceLanguage: 'English',
    targetLanguage: 'Tamil',
    question: 'What are the balancing invariants of a Red-Black Tree during insertion?',
    referenceAnswer: 'Every node is red or black, root is black, red nodes cannot have red children, and all paths from root to null leaves have the same black height.',
    directTranslation: 'சிவப்பு-கருப்பு மரத்தின் சமநிலை விதிகள் என்ன? சிவப்பு கிளைகள் கருப்பு பழங்களை தர வேண்டும்...',
    contextAwareResponse: 'Red-Black Tree என்பது ஒரு Self-Balancing Binary Search Tree ஆகும். Insertion-இன் போது இது 5 முக்கிய விதிகளைப் பின்பற்றுகிறது: 1) ஒவ்வொரு Node-உம் Red அல்லது Black ஆக இருக்க வேண்டும், 2) Root Node எப்போதும் Black-ஆக இருக்க வேண்டும், 3) Red Node-இன் குழந்தைகள் எப்போதும் Black-ஆக இருக்க வேண்டும் (No two consecutive Red nodes), 4) Root-லிருந்து எந்த ஒரு Leaf Node-க்கும் செல்லும் பாதையில் Black Nodes எண்ணிக்கை (Black-Height) சமமாக இருக்க வேண்டும்...',
    expectedTerms: ['Red-Black Tree', 'Binary Search Tree', 'Self-Balancing', 'Root Node', 'Black-Height', 'Tree Rotations'],
    createdAt: '2026-08-15T11:45:00.000Z',
  },
  {
    id: 'case_013',
    subject: 'Operating Systems',
    topic: 'Page Replacement Algorithms',
    sourceLanguage: 'English',
    targetLanguage: 'Gujarati',
    question: 'How does the LRU (Least Recently Used) page replacement algorithm handle page faults?',
    referenceAnswer: 'When memory is full and a page fault occurs, LRU evicts the page in RAM that has not been accessed for the longest time, often implemented with doubly linked lists and hash maps.',
    directTranslation: 'ઓછામાં ઓછા તાજેતરમાં વપરાયેલ પાનું બદલવાની પદ્ધતિ પાનાંની ભૂલને કેવી રીતે સંભાળે છે? પુસ્તકનું પાનું ફાટી જાય ત્યારે...',
    contextAwareResponse: 'Operating System માં જ્યારે Page Fault સર્જાય છે (માંગવામાં આવેલ Page RAM માં હાજર ન હોય) અને Frames ભરેલા હોય, ત્યારે LRU (Least Recently Used) Algorithm તે Page ને Evict કરે છે જેનો ભૂતકાળમાં સૌથી લાંબા સમયથી ઉપયોગ થયો નથી. આને Doubly Linked List અને Hash Map ના સંયોજનથી O(1) time complexity માં implement કરી શકાય છે...',
    expectedTerms: ['LRU Page Replacement', 'Page Fault', 'Frames', 'RAM', 'Doubly Linked List', 'Eviction'],
    createdAt: '2026-08-15T12:00:00.000Z',
  },
  {
    id: 'case_014',
    subject: 'Computer Networks',
    topic: 'DNS Resolution Process',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'Step-by-step explain how recursive and iterative DNS queries resolve a domain name into an IP address.',
    referenceAnswer: 'Client queries recursive resolver. Resolver queries Root Server (returns TLD), TLD Server (returns Authoritative), and Authoritative Server (returns final A/AAAA record).',
    directTranslation: 'डीएनएस समाधान प्रक्रिया का वर्णन करें। नाम सर्वर ग्राहक से बात करके पता निकालता है...',
    contextAwareResponse: 'जब आप ब्राउज़र में domain name (जैसे www.google.com) टाइप करते हैं, तो DNS Resolution निम्नानुसार कार्य करता है: 1) Local Cache (Browser/OS) चेक होता है। 2) यदि अनुपस्थित हो, तो Recursive Resolver (ISP/Cloudflare 1.1.1.1) को query भेजी जाती है। 3) Resolver सबसे पहले Root DNS Server (.) से पूछता है जो .com TLD Server का पता देता है। 4) TLD Server उस domain के Authoritative Name Server का पता देता है। 5) Authoritative Server अंतिम IP Address (A/AAAA record) लौटाता है...',
    expectedTerms: ['DNS Resolution', 'Recursive Query', 'Iterative Query', 'Root Server', 'TLD Server', 'Authoritative Server', 'IP Address'],
    createdAt: '2026-08-15T12:15:00.000Z',
  },
  {
    id: 'case_015',
    subject: 'Software Engineering',
    topic: 'Microservices vs Monoliths',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    question: 'Compare monolithic architecture with microservices architecture regarding deployment, scalability, and network latency.',
    referenceAnswer: 'Monoliths deploy single codebase with low in-process call latency but scaled as entire unit. Microservices deploy decoupled services independently via network APIs, increasing operational complexity and network overhead.',
    directTranslation: 'మోనోలిథ్ మరియు మైక్రోసర్వీసెస్ మధ్య భేదం ఏమిటి? ఒకే పెద్ద రాయి మరియు చిన్న రాళ్ళు...',
    contextAwareResponse: 'Monolithic Architecture లో అప్లికేషన్ యొక్క UI, Business Logic మరియు Database access అన్నీ ఒకే Codebase మరియు process గా ఉంటాయి. దీనిలో in-memory calls వేగంగా ఉంటాయి, కానీ చిన్న మార్పు చేసినా పూర్తి app ని redeploy చేయాలి. Microservices Architecture లో ప్రతి business capability (ఉదా: Auth, Payment, Catalog) స్వతంత్రంగా deploy చేయదగిన విడివిడి services గా ఉంటాయి. ఇవి REST లేదా gRPC APIs ద్వారా కమ్యూనికేట్ అవుతాయి, స్వతంత్ర Scalability అందిస్తాయి కానీ Network Latency మరియు Distributed Systems సంక్లిష్టత పెరుగుతుంది...',
    expectedTerms: ['Monolithic Architecture', 'Microservices', 'Deployment', 'Scalability', 'Network Latency', 'REST / gRPC'],
    createdAt: '2026-08-15T12:30:00.000Z',
  },
  {
    id: 'case_016',
    subject: 'Algorithms',
    topic: 'Dynamic Programming vs Divide & Conquer',
    sourceLanguage: 'English',
    targetLanguage: 'Tamil',
    question: 'What is the difference between Dynamic Programming and Divide and Conquer algorithms regarding subproblems?',
    referenceAnswer: 'Divide and conquer breaks problem into independent subproblems (Merge Sort). Dynamic programming solves overlapping subproblems with optimal substructure by memoizing or tabulating results.',
    directTranslation: 'டைனமிக் புரோகிராமிங் மற்றும் பிரித்து வெல்லும் முறையின் வேறுபாடு என்ன? கணக்குகளை சிறு துண்டுகளாக வெட்டுவது...',
    contextAwareResponse: 'Divide and Conquer (பிரித்து வெல்லும் முறை) என்பது ஒரு பிரச்சனையை முற்றிலும் தனித்தனியான (independent) துணைப் பிரச்சனைகளாகப் பிரித்து தீர்க்கிறது (உதாரணம்: Merge Sort). இதற்கு மாறாக, Dynamic Programming (DP) என்பது ஒன்றுடன் ஒன்று இணையும் (overlapping subproblems) துணைப் பிரச்சனைகள் மற்றும் Optimal Substructure பண்பு கொண்ட பிரச்சனைகளுக்குப் பயன்படுகிறது. இது மீண்டும் மீண்டும் அதே கணக்கீட்டைச் செய்யாமல் Memoization (Top-down) அல்லது Tabulation (Bottom-up) மூலம் சேமித்து வைக்கிறது (உதாரணம்: 0/1 Knapsack, Longest Common Subsequence)...',
    expectedTerms: ['Dynamic Programming', 'Divide and Conquer', 'Overlapping Subproblems', 'Optimal Substructure', 'Memoization', 'Tabulation'],
    createdAt: '2026-08-15T12:45:00.000Z',
  },
  {
    id: 'case_017',
    subject: 'DBMS',
    topic: 'Database Sharding vs Replication',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'How does horizontal database sharding differ from master-slave replication in database scaling?',
    referenceAnswer: 'Replication copies entire database across nodes for high read throughput and failover redundancy. Sharding partitions table rows across different nodes using shard keys for horizontal write scaling.',
    directTranslation: 'डेटाबेस के टुकड़े करना और नकल बनाना में क्या अंतर है? एक में शीशा टूटता है और दूसरे में फोटोकॉपी होती है...',
    contextAwareResponse: 'Database Replication (जैसे Primary-Replica architecture) में संपूर्ण डेटाबेस की प्रतियां multiple servers पर sync की जाती हैं। यह High Availability और Read operations को scale करने के लिए आदर्श है। इसके विपरीत, Database Sharding (Horizontal Partitioning) में एक बहुत बड़ी table के rows को Shard Key (जैसे User_ID hash) के आधार पर अलग-अलग physical database instances में विभाजित कर दिया जाता है, जिससे Write throughput और storage capacity scale होती है...',
    expectedTerms: ['Database Sharding', 'Replication', 'Horizontal Partitioning', 'Primary-Replica', 'Shard Key', 'Write Scalability'],
    createdAt: '2026-08-15T13:00:00.000Z',
  },
  {
    id: 'case_018',
    subject: 'Machine Learning',
    topic: 'Bias-Variance Tradeoff',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    question: 'Explain the bias-variance tradeoff and its relationship to underfitting and overfitting.',
    referenceAnswer: 'High bias causes underfitting due to overly simplistic model assumptions (high training error). High variance causes overfitting due to model sensitivity to training noise (high test error).',
    directTranslation: 'పక్షపాతం మరియు వైవిధ్యం మధ్య వ్యాపారం ఏమిటి? బయాస్ అనేది అనుమానం మరియు వేరియెన్స్ అనేది రంగు...',
    contextAwareResponse: 'Machine Learning లో Bias-Variance Tradeoff అనేది మోడల్ యొక్క Generalization సామర్థ్యాన్ని నిర్ణయించే అత్యంత ముఖ్యమైన భావన. High Bias అంటే మోడల్ చాలా సరళమైన ఊహలను కలిగి ఉండటం (Underfitting), దీనివల్ల Training మరియు Testing రెండింటిలోనూ ఎక్కువ Error వస్తుంది. High Variance అంటే మోడల్ Training డేటాలోని స్వల్ప శబ్దాన్ని (noise) కూడా ఎక్కువగా నేర్చుకోవడం (Overfitting), దీనివల్ల Training Error తక్కువగా ఉన్నప్పటికీ Test Error చాలా ఎక్కువగా ఉంటుంది...',
    expectedTerms: ['Bias-Variance Tradeoff', 'High Bias', 'High Variance', 'Underfitting', 'Overfitting', 'Generalization Error'],
    createdAt: '2026-08-15T13:15:00.000Z',
  },
  {
    id: 'case_019',
    subject: 'Programming',
    topic: 'Asynchronous Event Loop in Node.js',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'How does the single-threaded Event Loop in Node.js handle non-blocking I/O operations with libuv?',
    referenceAnswer: 'Node.js runs single-threaded JS execution stack, delegating asynchronous I/O (files, network) to libuv thread pool and OS kernel, queuing callbacks into microtask and macrotask phases.',
    directTranslation: 'नोड जेएस में घटना का चक्कर कैसे घूमता है और धागों के बिना कैसे काम करता है? यह पहिए की तरह चक्कर लगाता है...',
    contextAwareResponse: 'Node.js single-threaded JavaScript execution engine (V8) पर चलता है, लेकिन libuv library के C++ Thread Pool और OS kernel abstractions (epoll/kqueue) का उपयोग करके non-blocking asynchronous I/O प्रदान करता है। जब कोई async operation (जैसे database query या file read) शुरू होता है, तो main thread ब्लॉक नहीं होता। Operation पूरा होने पर callback को Event Loop की उपयुक्त Phase (Timers, Pending Callbacks, Poll, Check) के Task Queue में डाला जाता है...',
    expectedTerms: ['Event Loop', 'Single-threaded', 'Non-blocking I/O', 'libuv', 'Call Stack', 'Callback Queue', 'Microtask'],
    createdAt: '2026-08-15T13:30:00.000Z',
  },
  {
    id: 'case_020',
    subject: 'Cyber Security',
    topic: 'SQL Injection Prevention',
    sourceLanguage: 'English',
    targetLanguage: 'Bengali',
    question: 'Why are parameterized queries and prepared statements immune to SQL Injection vulnerabilities?',
    referenceAnswer: 'Prepared statements separate SQL query logic from data inputs by compiling the statement syntax first, treating user input strictly as literal parameter values rather than executable code.',
    directTranslation: 'প্রস্তুত বিবৃতি কেন এসকিউএল ইনজেকশন প্রতিরোধ করে? এটি রোগীর ইঞ্জেকশনের মতো ওষুধ দেয়...',
    contextAwareResponse: 'SQL Injection তখন ঘটে যখন আক্রমণকারীর অসৎ ইনপুট সরাসরি SQL Query স্ট্রিং-এর সাথে যুক্ত (concatenate) হয়ে ডেটাবেস সার্ভারে নির্বাহ হয়। Prepared Statements এবং Parameterized Queries ব্যবহারের ফলে Database Engine প্রথমে Query-এর Syntax ও Execution Plan কম্পাইল করে নেয়। পরবর্তীতে ব্যবহারকারীর দেওয়া ইনপুটকে কেবলমাত্র Literal Data Parameter হিসেবে দেখা হয়, কখনও Executable SQL Code হিসেবে নয়...',
    expectedTerms: ['SQL Injection', 'Prepared Statements', 'Parameterized Queries', 'Query Compilation', 'Sanitization'],
    createdAt: '2026-08-15T13:45:00.000Z',
  },
  {
    id: 'case_021',
    subject: 'Operating Systems',
    topic: 'Virtual Memory & Paging',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    question: 'How does the Memory Management Unit (MMU) use Page Tables and TLB (Translation Lookaside Buffer) to translate virtual addresses?',
    referenceAnswer: 'MMU takes virtual address (page number + offset), checks high-speed TLB cache for physical frame mapping; on TLB miss, walks page table in RAM, updates TLB, and generates physical address.',
    directTranslation: 'మెమరీ మేనేజ్‌మెంట్ యూనిట్ పుస్తకం పేజీల పట్టికను ఉపయోగించి వర్చువల్ చిరునామాలను ఎలా మారుస్తుంది? చిరునామా కవరుపై రాసినట్లు...',
    contextAwareResponse: 'Hardware లోని Memory Management Unit (MMU) CPU విడుదల చేసిన Virtual Address ను Physical RAM Address గా మారుస్తుంది. Virtual Address లో Page Number మరియు Offset ఉంటాయి. వేగం కోసం, MMU మొదట TLB (Translation Lookaside Buffer - ఒక high-speed hardware cache) ను తనిఖీ చేస్తుంది (TLB Hit). TLB లో లేకపోతే (TLB Miss), అది RAM లోని Page Table ను శోధించి Frame Number పొందుతుంది మరియు TLB ని update చేస్తుంది...',
    expectedTerms: ['Memory Management Unit (MMU)', 'Page Table', 'TLB (Translation Lookaside Buffer)', 'Virtual Address', 'Physical Frame', 'Page Offset'],
    createdAt: '2026-08-15T14:00:00.000Z',
  },
  {
    id: 'case_022',
    subject: 'Computer Networks',
    topic: 'BGP (Border Gateway Protocol)',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'How does BGP (Border Gateway Protocol) route packets across Autonomous Systems (AS) on the global Internet?',
    referenceAnswer: 'BGP is an exterior gateway path-vector protocol using TCP port 179 to exchange reachable network prefixes and AS-Path attributes between distinct administrative Autonomous Systems.',
    directTranslation: 'सीमा द्वार प्रोटोकॉल स्वायत्त प्रणालियों में पैकेट कैसे भेजता है? यह सीमा पर खड़े सिपाही की तरह पासपोर्ट चेक करता है...',
    contextAwareResponse: 'BGP (Border Gateway Protocol) पूरे इंटरनेट का मुख्य Routing Protocol है जो स्वतंत्र Autonomous Systems (AS - जैसे ISPs, Google, Cloudflare) के बीच Routing जानकारी साझा करता है। यह एक Path Vector Protocol है जो TCP Port 179 पर काम करता है। BGP निर्णय केवल सबसे छोटे रास्ते (hop count) पर नहीं, बल्कि AS-Path attributes, Local Preference और peering business policies के आधार पर लेता है...',
    expectedTerms: ['BGP (Border Gateway Protocol)', 'Autonomous System (AS)', 'Path Vector Protocol', 'AS-Path', 'Peering', 'Prefix Announcement'],
    createdAt: '2026-08-15T14:15:00.000Z',
  },
  {
    id: 'case_023',
    subject: 'Artificial Intelligence',
    topic: 'Gradient Descent Optimization',
    sourceLanguage: 'English',
    targetLanguage: 'Tamil',
    question: 'How does Adam Optimizer improve upon Stochastic Gradient Descent with Momentum and RMSprop?',
    referenceAnswer: 'Adam computes adaptive learning rates by maintaining exponential moving averages of both past gradients (first moment/momentum) and squared gradients (second moment/RMSprop) with bias correction.',
    directTranslation: 'ஆடம் ஆப்டிமைசர் எப்படி சாய்வு இறக்கத்தை சரிசெய்கிறது? மனிதன் மலையிலிருந்து கீழே உருண்டு ஓடுவது போல...',
    contextAwareResponse: 'Adam (Adaptive Moment Estimation) Optimizer என்பது Deep Learning-இல் Weights-ஐ வேகமாக மற்றும் நிலையாக புதுப்பிக்கப் பயன்படும் மிகச் சிறந்த Optimization Algorithm ஆகும். இது Momentum (முந்தைய Gradients-இன் First Moment - சராசரி திசை) மற்றும் RMSprop (முந்தைய Gradients-இன் Second Moment - வர்க்க சராசரி கொண்டு Learning Rate-ஐ சரிசெய்தல்) இரண்டின் நன்மைகளையும் ஒருங்கிணைக்கிறது. மேலும் தொடக்க படிகளில் Bias Correction செய்து Zero- நோக்கி சாய்வதைத் தவிர்க்கிறது...',
    expectedTerms: ['Adam Optimizer', 'Stochastic Gradient Descent', 'Momentum', 'RMSprop', 'Learning Rate', 'Bias Correction'],
    createdAt: '2026-08-15T14:30:00.000Z',
  },
  {
    id: 'case_024',
    subject: 'DBMS',
    topic: 'Two-Phase Locking (2PL)',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    question: 'How does Strict Two-Phase Locking (Strict 2PL) ensure serializability and prevent cascading aborts?',
    referenceAnswer: 'Strict 2PL requires growing phase (acquiring locks) and shrinking phase, holding all exclusive write locks until transaction commits or aborts, eliminating dirty reads and cascading rollbacks.',
    directTranslation: 'రెండు దశల లాకింగ్ పద్ధతి సీరియలైజేషన్ ను ఎలా ఇస్తుంది? తలుపుకు రెండు తాళాలు వేయడం ద్వారా...',
    contextAwareResponse: 'Strict Two-Phase Locking (Strict 2PL) అనేది Concurrency Control లో Conflict Serializability ని హామీ ఇచ్చే ముఖ్యమైన protocol. ఇది రెండు దశల్లో పనిచేస్తుంది: 1) Growing Phase: Transaction తనకు కావలసిన Shared (Read) మరియు Exclusive (Write) Locks ని పొందుతుంది. 2) Shrinking Phase: Locks విడుదల చేయబడతాయి. Strict 2PL ప్రత్యేకత ఏమిటంటే, Transaction Commit లేదా Abort అయ్యేంతవరకు అన్ని Exclusive Locks ని అట్టిపెట్టుకుంటుంది. దీనివల్ల Dirty Read సమస్య ఉండదు మరియు Cascading Aborts పూర్తిగా నివారించబడతాయి...',
    expectedTerms: ['Strict 2PL', 'Two-Phase Locking', 'Growing Phase', 'Shrinking Phase', 'Exclusive Locks', 'Cascading Aborts', 'Serializability'],
    createdAt: '2026-08-15T14:45:00.000Z',
  },
  {
    id: 'case_025',
    subject: 'Cloud Computing',
    topic: 'Serverless Computing & Cold Starts',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'What is a cold start in serverless FaaS (AWS Lambda / Google Cloud Functions) and how can it be mitigated?',
    referenceAnswer: 'Cold start latency occurs when a cloud provider spins up a new container microVM, initializes runtime, and downloads handler code upon first invocation after idle scale-to-zero.',
    directTranslation: 'क्लाउड में ठंडी शुरुआत क्या है और इसे कैसे गर्म किया जाए? जब कंप्यूटर सर्दियों में ठंडा पड़ जाता है...',
    contextAwareResponse: 'Serverless Functions (FaaS जैसे AWS Lambda या Google Cloud Functions) जब idle होकर scale-to-zero हो जाते हैं, तब पहली नई request आने पर cloud infrastructure को नया container/microVM initialize करना, runtime लोड करना और dependencies load करनी पड़ती हैं; इस प्रारंभिक latency delay को Cold Start कहते हैं। इसे कम करने के तरीके: Provisioned Concurrency, lightweight runtimes (Node.js/Go vs heavy JVM), bundle size mini-fication, और periodic ping warmers...',
    expectedTerms: ['Serverless', 'Cold Start Latency', 'FaaS (Function as a Service)', 'Container Initialization', 'Provisioned Concurrency', 'Scale-to-Zero'],
    createdAt: '2026-08-15T15:00:00.000Z',
  },
  {
    id: 'case_026',
    subject: 'Data Structures',
    topic: 'Trie (Prefix Tree)',
    sourceLanguage: 'English',
    targetLanguage: 'Marathi',
    question: 'How does a Trie data structure achieve O(L) time complexity for search and autocomplete suggestions?',
    referenceAnswer: 'Trie nodes store character transitions rather than full keys; search follows edges corresponding to prefix characters of length L, independent of the total number of dictionary words N.',
    directTranslation: 'ट्राय डेटा स्ट्रक्चर झाडासारखे शब्द कसे शोधते? प्रत्येक पानावर अक्षरे लिहून...',
    contextAwareResponse: 'Trie (Prefix Tree) हे एक विशिष्ट Tree Data Structure आहे जे Strings चा संग्रह कार्यक्षमतेने store करण्यासाठी वापरले जाते. यामध्ये Node संपूर्ण शब्द साठवत नाही, तर प्रत्येक edge एका character चे प्रतिनिधित्व करते. शोधल्या जाणाऱ्या शब्दाची लांबी L असल्यास, Trie मध्ये Search time complexity O(L) असते, जी डिक्शनरीमधील एकूण शब्दांच्या संख्येवर (N) अवलंबून नसते. यामुळे Google Search autocomplete आणि spell-checkers मध्ये Trie चा मोठ्या प्रमाणावर वापर होतो...',
    expectedTerms: ['Trie (Prefix Tree)', 'Time Complexity O(L)', 'Autocomplete', 'Character Edges', 'Root to Leaf Path'],
    createdAt: '2026-08-15T15:15:00.000Z',
  },
  {
    id: 'case_027',
    subject: 'Programming',
    topic: 'Rust Ownership & Borrow Checker',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    question: 'How does the Rust borrow checker achieve memory safety without a runtime Garbage Collector?',
    referenceAnswer: 'Rust enforces compile-time ownership invariants: each value has single owner, drops when owner goes out of scope, allowing either multiple immutable references (&T) or one mutable reference (&mut T) at a time.',
    directTranslation: 'రస్ట్ అప్పు తీసుకునే తనిఖీ యంత్రం మెమరీ భద్రతను ఎలా తెస్తుంది? ఎవరైనా అప్పు తీసుకుంటే వడ్డీ కట్టాలి...',
    contextAwareResponse: 'Rust ప్రోగ్రామింగ్ భాష Runtime Garbage Collector లేకుండానే Compile-Time లోనే Memory Safety ని హామీ ఇస్తుంది. దీనికి కారణం Ownership & Borrow Checker నియమాలు: 1) ప్రతి విలువకు (value) ఒకే Owner variable ఉంటుంది. 2) Owner scope దాటిపోగానే memory స్వయంచాలకంగా free (drop) అవుతుంది. 3) Borrow Checker ఒకే సమయంలో ఎన్ని అయినా Immutable References (&T) లేదా కేవలం ఒకే ఒక Mutable Reference (&mut T) ను మాత్రమే అనుమతిస్తుంది. దీనివల్ల Dangling Pointers మరియు Data Races సంభవించవు...',
    expectedTerms: ['Rust Borrow Checker', 'Ownership Model', 'Garbage Collector Free', 'Immutable Reference (&T)', 'Mutable Reference (&mut T)', 'Dangling Pointer Prevention'],
    createdAt: '2026-08-15T15:30:00.000Z',
  },
  {
    id: 'case_028',
    subject: 'Algorithms',
    topic: 'NP-Completeness and Reductions',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'What does it mean for a decision problem to be NP-Complete, and how does polynomial-time reduction prove it?',
    referenceAnswer: 'A problem is NP-Complete if it belongs to NP (solutions verifiable in polynomial time) and is NP-Hard (every problem in NP polynomial-time reduces to it). Proved by reducing a known NP-Complete problem (like 3-SAT) to it.',
    directTranslation: 'एनपी पूर्ण निर्णय समस्या का क्या अर्थ है? यह बहुत कठिन समस्या है जिसका उत्तर नहीं मिलता...',
    contextAwareResponse: 'Computational Complexity Theory में कोई Decision Problem तब NP-Complete कहलाता है जब: 1) वह NP Class में हो (अर्थात यदि कोई संभावित समाधान दिया जाए तो उसे Polynomial Time O(n^k) में verify किया जा सके)। 2) वह NP-Hard हो (अर्थात NP का प्रत्येक अन्य problem polynomial-time reduction द्वारा इसमें रूपांतरित किया जा सके)। किसी नए problem को NP-Complete सिद्ध करने के लिए किसी ज्ञात NP-Complete problem (जैसे 3-SAT या Circuit-SAT) को polynomial time में नए problem में reduce करके दिखाया जाता है...',
    expectedTerms: ['NP-Complete', 'NP-Hard', 'Polynomial-Time Reduction', 'Decision Problem', 'Cook-Levin Theorem', 'Verification'],
    createdAt: '2026-08-15T15:45:00.000Z',
  },
  {
    id: 'case_029',
    subject: 'Cyber Security',
    topic: 'Cross-Site Scripting (XSS) Prevention',
    sourceLanguage: 'English',
    targetLanguage: 'Tamil',
    question: 'What is Stored vs Reflected XSS, and how do Content Security Policy (CSP) and output encoding prevent exploitation?',
    referenceAnswer: 'Stored XSS permanently saves malicious script in database; Reflected bounces unvalidated payload off URL/request. Mitigated by context-aware HTML entity encoding and strict CSP HTTP headers prohibiting inline scripts.',
    directTranslation: 'குறுக்கு தள ஸ்கிரிப்டிங் எப்படி தடுக்கப்படுகிறது? இணையதளங்கள் ஒன்றையொன்று தாக்காமல் இருக்க வேலி போடுவது...',
    contextAwareResponse: 'Cross-Site Scripting (XSS) என்பது பயனர் உலாவியில் (Browser) தாக்குபவரின் தீங்கிழைக்கும் JavaScript குறியீடு இயங்கும் பாதிப்பு ஆகும். Stored XSS-இல் குறியீடு Database-இல் நிரந்தரமாகச் சேமிக்கப்படுகிறது (Comments/Profile). Reflected XSS-இல் URL parameter வழியாக உடனடியாகத் திருப்பி விடப்படுகிறது. இதைத் தடுக்க: 1) Context-Aware Output Encoding (HTML Entities ஆக மாற்றுதல்), 2) Content Security Policy (CSP) Header-களை வழங்கி unauthorized inline scripts இயங்குவதைத் தடை செய்தல்...',
    expectedTerms: ['Cross-Site Scripting (XSS)', 'Stored XSS', 'Reflected XSS', 'Content Security Policy (CSP)', 'Output Encoding', 'Cookie HttpOnly'],
    createdAt: '2026-08-15T16:00:00.000Z',
  },
  {
    id: 'case_030',
    subject: 'Artificial Intelligence',
    topic: 'Retrieval-Augmented Generation (RAG)',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    question: 'How does a Retrieval-Augmented Generation (RAG) architecture combine vector embeddings and LLMs to prevent hallucinations?',
    referenceAnswer: 'RAG chunks documents, generates dense vector embeddings stored in a vector DB, performs cosine similarity search on user query, and injects retrieved context chunks into the LLM prompt to ground generation.',
    directTranslation: 'पुनर्प्राप्ति-संवर्धित पीढ़ी भ्रम को कैसे रोकती है? यह पुरानी किताबों को ढूँढकर ज्ञान देती है...',
    contextAwareResponse: 'Retrieval-Augmented Generation (RAG) Architecture Large Language Models (LLMs) में Hallucinations (गलत या काल्पनिक उत्तर) को रोकने के लिए External Knowledge Base को जोड़ता है। प्रक्रिया: 1) Technical Documents को छोटे Chunks में बाँटकर Embedding Model द्वारा Dense Vector Embeddings बनाई जाती हैं। 2) User Query आने पर Vector Database में Cosine Similarity Search द्वारा सर्वाधिक relevant context chunks खोजे जाते हैं। 3) इन retrieved chunks को Context-Aware Prompt के रूप में LLM को प्रदान किया जाता है, जिससे उत्तर factual और grounded रहता है...',
    expectedTerms: ['Retrieval-Augmented Generation (RAG)', 'Vector Embeddings', 'Cosine Similarity', 'Vector Database', 'Hallucination Mitigation', 'Context Injection'],
    createdAt: '2026-08-15T16:15:00.000Z',
  },
];

export const SEED_EVALUATION_REVIEWS: EvaluationReview[] = [
  {
    id: 'rev_001',
    caseId: 'case_001',
    reviewerId: 'user_admin_001',
    reviewerName: 'Dr. Priya Sharma (Lead Researcher)',
    directSemanticScore: 1,
    directTechnicalScore: 1,
    directTerminologyScore: 1,
    directFluencyScore: 2,
    directQualityScore: 1,
    contextSemanticScore: 5,
    contextTechnicalScore: 5,
    contextTerminologyScore: 5,
    contextFluencyScore: 5,
    contextQualityScore: 5,
    flags: {
      ambiguousTranslation: true,
      technicalError: true,
      meaningLoss: true,
      terminologyError: true,
      complexityMismatch: true,
    },
    notes: 'Method A translated "Thread" as sewing thread ("धागा") and "Race conditions" as running competition ("दौड़ की स्थिति"), destroying the entire operating systems concept. Method B accurately preserved "Thread", "Process", and "Race Condition" with natural Hindi grammatical binding.',
    createdAt: '2026-08-16T10:00:00.000Z',
  },
  {
    id: 'rev_002',
    caseId: 'case_002',
    reviewerId: 'user_admin_001',
    reviewerName: 'Dr. Priya Sharma (Lead Researcher)',
    directSemanticScore: 1,
    directTechnicalScore: 1,
    directTerminologyScore: 1,
    directFluencyScore: 2,
    directQualityScore: 1,
    contextSemanticScore: 5,
    contextTechnicalScore: 5,
    contextTerminologyScore: 5,
    contextFluencyScore: 5,
    contextQualityScore: 5,
    flags: {
      ambiguousTranslation: true,
      technicalError: true,
      meaningLoss: true,
      terminologyError: true,
      complexityMismatch: false,
    },
    notes: 'Direct machine translation interpreted "network socket" as an electrical wall socket and "handshake" as a literal human handshake. Context-aware prompting accurately preserved "Socket", "IP Address", and "Three-Way Handshake" in Telugu.',
    createdAt: '2026-08-16T10:30:00.000Z',
  },
  {
    id: 'rev_003',
    caseId: 'case_003',
    reviewerId: 'user_admin_001',
    reviewerName: 'Dr. Priya Sharma (Lead Researcher)',
    directSemanticScore: 2,
    directTechnicalScore: 1,
    directTerminologyScore: 1,
    directFluencyScore: 2,
    directQualityScore: 1,
    contextSemanticScore: 5,
    contextTechnicalScore: 5,
    contextTerminologyScore: 5,
    contextFluencyScore: 4,
    contextQualityScore: 5,
    flags: {
      ambiguousTranslation: true,
      technicalError: true,
      meaningLoss: true,
      terminologyError: true,
      complexityMismatch: true,
    },
    notes: 'In Tamil, Direct translation translated Overfitting as tight tailoring of clothes. Context-aware prompting explained high variance, generalization error, and L2 weight penalties with pristine technical clarity.',
    createdAt: '2026-08-16T11:00:00.000Z',
  },
  {
    id: 'rev_004',
    caseId: 'case_004',
    reviewerId: 'user_admin_001',
    reviewerName: 'Dr. Priya Sharma (Lead Researcher)',
    directSemanticScore: 2,
    directTechnicalScore: 2,
    directTerminologyScore: 1,
    directFluencyScore: 3,
    directQualityScore: 2,
    contextSemanticScore: 5,
    contextTechnicalScore: 5,
    contextTerminologyScore: 5,
    contextFluencyScore: 5,
    contextQualityScore: 5,
    flags: {
      ambiguousTranslation: true,
      technicalError: true,
      meaningLoss: true,
      terminologyError: true,
      complexityMismatch: false,
    },
    notes: 'Direct translation created confusion around "Separate Chaining" (translated as physical chain ropes). Context-aware prompt provided accurate algorithmic distinction with linked lists and open addressing.',
    createdAt: '2026-08-16T11:30:00.000Z',
  },
  {
    id: 'rev_005',
    caseId: 'case_005',
    reviewerId: 'user_admin_001',
    reviewerName: 'Dr. Priya Sharma (Lead Researcher)',
    directSemanticScore: 1,
    directTechnicalScore: 1,
    directTerminologyScore: 1,
    directFluencyScore: 2,
    directQualityScore: 1,
    contextSemanticScore: 5,
    contextTechnicalScore: 5,
    contextTerminologyScore: 5,
    contextFluencyScore: 5,
    contextQualityScore: 5,
    flags: {
      ambiguousTranslation: true,
      technicalError: true,
      meaningLoss: true,
      terminologyError: true,
      complexityMismatch: false,
    },
    notes: 'Deadlock literally translated to "మరణించిన తాళం" (dead lock/key). Method B explicitly maintained Coffman conditions with crisp explanations of Mutual Exclusion and Circular Wait.',
    createdAt: '2026-08-16T12:00:00.000Z',
  },
  {
    id: 'rev_006',
    caseId: 'case_011',
    reviewerId: 'user_admin_001',
    reviewerName: 'Dr. Priya Sharma (Lead Researcher)',
    directSemanticScore: 1,
    directTechnicalScore: 1,
    directTerminologyScore: 1,
    directFluencyScore: 2,
    directQualityScore: 1,
    contextSemanticScore: 5,
    contextTechnicalScore: 5,
    contextTerminologyScore: 5,
    contextFluencyScore: 5,
    contextQualityScore: 5,
    flags: {
      ambiguousTranslation: true,
      technicalError: true,
      meaningLoss: true,
      terminologyError: true,
      complexityMismatch: true,
    },
    notes: 'Direct translation translated "Memory leak" into physical water leaking and "Garbage Collection" into city sanitation truck sweeps. Context-aware prompt correctly treated heap references and mark-and-sweep phases.',
    createdAt: '2026-08-16T12:30:00.000Z',
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1788773651185_t6i9m',
    userId: 'user_student_001',
    title: 'What is a Deadlock in Operating Systems?',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    subject: 'Operating Systems',
    difficulty: 'INTERMEDIATE',
    createdAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    messages: [
      {
        id: 'msg_seed_1_u',
        conversationId: 'conv_1788773651185_t6i9m',
        sender: 'user',
        content: 'What is a Deadlock in Operating Systems and how does Mutual Exclusion cause it?',
        sourceLanguage: 'English',
        targetLanguage: 'Telugu',
        subject: 'Operating Systems',
        difficulty: 'INTERMEDIATE',
        timestamp: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
      },
      {
        id: 'msg_seed_1_a',
        conversationId: 'conv_1788773651185_t6i9m',
        sender: 'assistant',
        content: 'Operating Systems లో Deadlock అనేది రెండు లేదా అంతకంటే ఎక్కువ Processes వనరుల కోసం వేచి ఉండి, ఏ ప్రాసెస్ కూడా ముందుకు సాగలేని స్తంభించిన స్థితి.',
        sourceLanguage: 'English',
        targetLanguage: 'Telugu',
        subject: 'Operating Systems',
        difficulty: 'INTERMEDIATE',
        timestamp: new Date(Date.now() - 3600 * 1000 * 4 + 2000).toISOString(),
        structuredResponse: {
          definition: 'Operating Systems లో Deadlock అనేది బహుళ Processes వనరులను నిలుపుకొని ఇతర ప్రక్రియలు విడుదల చేసేంతవరకు నిరవధికంగా వేచి ఉండే నిశ్చల స్థితి.',
          quickAnswer: 'Deadlock ఏర్పడటానికి Coffman conditions (Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait) ఏకకాలంలో వర్తించాలి.',
          explanation: 'కంప్యూటర్ సైన్స్ లో Deadlock ను నివారించడానికి Banker\'s Algorithm మరియు Resource Allocation Graph (RAG) ఉపయోగిస్తారు.',
          analogy: 'ఒకే ఇరుకైన వంతెనపైకి ఇరువైపుల నుండి రెండు వాహనాలు (Processes) ఎదురెదురుగా వచ్చినప్పుడు, ఎవరూ వెనక్కి తగ్గకపోతే ట్రాఫిక్ పూర్తిగా నిలిచిపోతుంది.',
          example: '// Deadlock demonstration with Pthread mutex\npthread_mutex_lock(&lockA);\npthread_mutex_lock(&lockB);\n// Critical Section\npthread_mutex_unlock(&lockB);\npthread_mutex_unlock(&lockA);',
          stepByStep: [
            'Mutual Exclusion: ఒక సమయంలో ఒక Process మాత్రమే Resource ను కలిగి ఉంటుంది.',
            'Hold and Wait: ఒక Resource ను నిలుపుకొని మరొకటి అభ్యర్థించడం.',
            'Circular Wait: P1 -> P2 -> P3 -> P1 చక్రీయ నిరీక్షణ శృంఖల ఏర్పడటం.',
          ],
          keyPoints: [
            'సాంకేతిక పదం Deadlock ను అక్షరాలా అనువదించరాదు.',
            'Banker\'s Algorithm ద్వారా Safe State ను లెక్కించవచ్చు.',
          ],
          technicalTerms: [
            { term: 'Deadlock', translation: 'డెడ్‌లాక్', explanation: 'A state where processes wait mutually on resources held by each other' },
            { term: 'Mutual Exclusion', translation: 'మ్యూచువల్ ఎక్స్‌క్లూజన్', explanation: 'Only one process may hold a critical resource at once' },
          ],
          preservedTerms: ['Deadlock', 'Mutual Exclusion', 'Circular Wait', 'Process'],
          misconceptions: [
            'Deadlock మరియు Starvation ఒకటే అనుకోవడం పొరపాటు.',
          ],
        },
      },
    ],
  },
  {
    id: 'conv_1788774381341_bwedq',
    userId: 'user_student_001',
    title: 'Explain what is a Semaphore in Operating Systems and how Counting Semaphores work',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    subject: 'Operating Systems',
    difficulty: 'INTERMEDIATE',
    createdAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    messages: [
      {
        id: 'msg_seed_2_u',
        conversationId: 'conv_1788774381341_bwedq',
        sender: 'user',
        content: 'Explain what is a Semaphore in Operating Systems and how Counting Semaphores work',
        sourceLanguage: 'English',
        targetLanguage: 'Telugu',
        subject: 'Operating Systems',
        difficulty: 'INTERMEDIATE',
        timestamp: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
      },
      {
        id: 'msg_seed_2_a',
        conversationId: 'conv_1788774381341_bwedq',
        sender: 'assistant',
        content: 'Semaphore అనేది Concurrent Programming లో Critical Section యాక్సెస్‌ను సమన్వయం చేసే సింకనైజేషన్ వేరియబుల్.',
        sourceLanguage: 'English',
        targetLanguage: 'Telugu',
        subject: 'Operating Systems',
        difficulty: 'INTERMEDIATE',
        timestamp: new Date(Date.now() - 3600 * 1000 * 2 + 1500).toISOString(),
        structuredResponse: {
          definition: 'Semaphore అనేది Dijkstra రూపొందించిన ఒక integer variable, దీనిని కేవలం wait() (P) మరియు signal() (V) atomic operations ద్వారా మాత్రమే సవరించవచ్చు.',
          quickAnswer: 'Counting Semaphore లభ్యమయ్యే resource instances సంఖ్యను ట్రాక్ చేస్తుంది. సున్నా అయితే process బ్లాక్ అవుతుంది.',
          explanation: 'Operating Systems లో రేస్ కండిషన్స్ నివారించడానికి మరియు Producer-Consumer సమస్యను పరిష్కరించడానికి Semaphores ప్రాథమిక ఆధారం.',
          analogy: 'ఒక సూపర్ మార్కెట్‌లో 5 కస్టమర్ కార్ట్‌లు (Counting Semaphore = 5) ఉన్నాయని అనుకోండి. ప్రతి కస్టమర్ కార్ట్ తీసుకున్నప్పుడు కౌంట్ తగ్గుతుంది (wait), తిరిగి పెట్టినప్పుడు కౌంట్ పెరుగుతుంది (signal).',
          example: 'wait(semaphore S) {\n  while (S <= 0); // busy wait or sleep\n  S--;\n}\nsignal(semaphore S) {\n  S++;\n}',
          stepByStep: [
            'Binary Semaphore: విలువ 0 లేదా 1 మాత్రమే ఉంటుంది (Mutex లాంటిది).',
            'Counting Semaphore: అపరిమిత పరిధిలోని resource units ని పర్యవేక్షిస్తుంది.',
            'Wait() ఆపరేషన్ Semaphore విలువను తగ్గిస్తుంది, Signal() పెంచుతుంది.',
          ],
          keyPoints: [
            'Atomic operations వాడకం తప్పనిసరి.',
            'Deadlock రాకుండా signal order పాటించాలి.',
          ],
          technicalTerms: [
            { term: 'Semaphore', translation: 'సెమాఫోర్', explanation: 'Synchronization signaling primitive' },
            { term: 'Critical Section', translation: 'క్రిటికల్ సెక్షన్', explanation: 'Protected code region accessing shared state' },
          ],
          preservedTerms: ['Semaphore', 'Counting Semaphore', 'Critical Section'],
          misconceptions: [
            'Semaphore మరియు Mutex పూర్తిగా ఒకటే అనుకోవడం తప్పు.',
          ],
        },
      },
    ],
  },
  {
    id: 'conv_1788775100000_c3po9',
    userId: 'user_student_001',
    title: 'How does B+ Tree Indexing optimize DBMS range queries?',
    sourceLanguage: 'English',
    targetLanguage: 'Telugu',
    subject: 'DBMS',
    difficulty: 'ADVANCED',
    createdAt: new Date(Date.now() - 3600 * 1000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 1).toISOString(),
    messages: [
      {
        id: 'msg_seed_3_u',
        conversationId: 'conv_1788775100000_c3po9',
        sender: 'user',
        content: 'How does B+ Tree Indexing optimize DBMS range queries compared to standard B-Trees?',
        sourceLanguage: 'English',
        targetLanguage: 'Telugu',
        subject: 'DBMS',
        difficulty: 'ADVANCED',
        timestamp: new Date(Date.now() - 3600 * 1000 * 1).toISOString(),
      },
      {
        id: 'msg_seed_3_a',
        conversationId: 'conv_1788775100000_c3po9',
        sender: 'assistant',
        content: 'B+ Tree లో అన్ని data records కేవలం leaf nodes లోనే నిల్వ చేయబడి, leaf nodes అన్నీ doubly/singly linked list తో అనుసంధానించబడి ఉంటాయి.',
        sourceLanguage: 'English',
        targetLanguage: 'Telugu',
        subject: 'DBMS',
        difficulty: 'ADVANCED',
        timestamp: new Date(Date.now() - 3600 * 1000 * 1 + 1800).toISOString(),
        structuredResponse: {
          definition: 'B+ Tree అనేది self-balancing n-ary search tree, ఇందులో internal nodes కేవలం keys/pointers ను మాత్రమే కలిగి ఉండి, leaf nodes వాస్తవ data pointers ను linked list రూపంలో భద్రపరుస్తాయి.',
          quickAnswer: 'Range queries సమయంలో leaf nodes లోని sequential linked list ద్వారా వేగంగా traversal జరుగుతుంది, internal nodes ను మళ్లీ మళ్లీ సందర్శించాల్సిన అవసరం ఉండదు.',
          explanation: 'Standard B-Tree లో ప్రతి node లో keys మరియు data pointers ఉండటం వల్ల node capacity తగ్గుతుంది. B+ Tree లో internal nodes ఎక్కువ keys ని hold చేయడం వలన tree height గణనీయంగా తగ్గుతుంది, దీనివల్ల Disk I/O operations బాగా తగ్గుతాయి.',
          analogy: 'ఒక పెద్ద డిక్షనరీ లేదా ఎన్‌సైక్లోపీడియాను ఊహించండి: ఇండెక్స్ పేజీలు (Internal Nodes) కేవలం మార్గదర్శకాలు మాత్రమే, అన్ని వాస్తవ నిర్వచనాలు చివరి విభాగంలో పేజీల వారీగా వరుసగా అమర్చబడి ఉంటాయి.',
          example: '-- SQL Range Query utilizing B+ Tree Index\nSELECT * FROM Students \nWHERE graduation_year BETWEEN 2024 AND 2026;\n-- B+ Tree traverses root to start leaf, then follows sequential leaf pointers!',
          stepByStep: [
            'Root to Leaf Search: O(log N) సమయంతో మొదటి range key ని కనుగొంటుంది.',
            'Leaf Pointer Traversal: O(K) సమయంలో వరుసగా range లోని అన్ని అంశాలను సంగ్రహిస్తుంది.',
            'Disk Block Efficiency: అధిక Fan-out కారణంతో Cache Misses తగ్గిపోతాయి.',
          ],
          keyPoints: [
            'B+ Tree leaf nodes ఎల్లప్పుడూ ఒకే లోతు (balanced height) లో ఉంటాయి.',
            'MySQL InnoDB క్లస్టర్డ్ ఇండెక్స్ కోసం B+ Tree ని ప్రామాణికంగా వాడుతుంది.',
          ],
          technicalTerms: [
            { term: 'B+ Tree', translation: 'బి+ ట్రీ', explanation: 'N-ary search tree with linked leaf nodes for range scans' },
            { term: 'Range Query', translation: 'రేంజ్ క్వెరీ', explanation: 'Query searching between continuous boundaries' },
          ],
          preservedTerms: ['B+ Tree Indexing', 'Range Queries', 'Disk I/O', 'Leaf Nodes'],
          misconceptions: [
            'B-Tree మరియు B+ Tree ఒకే సంఖ్యలో Disk Reads తీసుకుంటాయని అనుకోవడం.',
          ],
        },
      },
    ],
  },
];

